inventory:
  plugin: SimpleInventory
  options:
    host_file: ./14.nornir/src/08.nornir_scrapli_send_commands/inventory/hosts.yaml
    group_file: ./14.nornir/src/08.nornir_scrapli_send_commands/inventory/groups.yaml
    defaults_file: ./14.nornir/src/08.nornir_scrapli_send_commands/inventory/defaults.yaml
logging:
  enabled: true
runner:
  plugin: threaded
  options:
    num_workers: 20
