# ruff: noqa
# mypy: ignore-errors
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scrapli_grpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "scrapli_grpc.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12scrapli_grpc.proto\x12\x13\x61pp.scrapli_grpc.v1"\x8b\x01\n\x04Host\x12\x0c\n\x04host\x18\n \x01(\t\x12/\n\x08platform\x18\x14 \x01(\x0e\x32\x1d.app.scrapli_grpc.v1.Platform\x12\x15\n\rauth_username\x18\x1e \x01(\t\x12\x15\n\rauth_password\x18( \x01(\t\x12\x16\n\x0e\x61uth_secondary\x18\x32 \x01(\t"C\n\x07\x43ommand\x12\'\n\x04host\x18\n \x01(\x0b\x32\x19.app.scrapli_grpc.v1.Host\x12\x0f\n\x07\x63ommand\x18\x14 \x01(\t"c\n\x06Result\x12\x0c\n\x04host\x18\n \x01(\t\x12\x15\n\rchannel_input\x18\x14 \x01(\t\x12\x0e\n\x06result\x18\x1e \x01(\t\x12\x14\n\x0c\x65lapsed_time\x18( \x01(\x02\x12\x0e\n\x06\x66\x61iled\x18\x32 \x01(\x08*m\n\x08Platform\x12\x14\n\x10PLATFORM_DEFAULT\x10\x00\x12\x18\n\x14PLATFORM_CISCO_IOSXE\x10\n\x12\x18\n\x14PLATFORM_CISCO_IOSXR\x10\x14\x12\x17\n\x13PLATFORM_HUAWEI_VRP\x10\x1e\x32\xac\x01\n\x0eScrapliService\x12H\n\x0bSendCommand\x12\x1c.app.scrapli_grpc.v1.Command\x1a\x1b.app.scrapli_grpc.v1.Result\x12P\n\x0fSendCommandChat\x12\x1c.app.scrapli_grpc.v1.Command\x1a\x1b.app.scrapli_grpc.v1.Result(\x01\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "scrapli_grpc_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PLATFORM"]._serialized_start = 355
    _globals["_PLATFORM"]._serialized_end = 464
    _globals["_HOST"]._serialized_start = 44
    _globals["_HOST"]._serialized_end = 183
    _globals["_COMMAND"]._serialized_start = 185
    _globals["_COMMAND"]._serialized_end = 252
    _globals["_RESULT"]._serialized_start = 254
    _globals["_RESULT"]._serialized_end = 353
    _globals["_SCRAPLISERVICE"]._serialized_start = 467
    _globals["_SCRAPLISERVICE"]._serialized_end = 639
# @@protoc_insertion_point(module_scope)
