inventory:
  plugin: SimpleInventory
  options:
    host_file: ./c14_nornir/src/05.custom_jinja/inventory/hosts.yaml
    group_file: ./c14_nornir/src/05.custom_jinja/inventory/groups.yaml
    defaults_file: ./c14_nornir/src/05.custom_jinja/inventory/defaults.yaml
logging:
  enabled: True
  level: DEBUG
  to_console: True
runner:
  plugin: threaded
  options:
    num_workers: 20
