# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'enum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nenum.proto\x12\x08\x61pp.enum\"-\n\tPingReply\x12 \n\x06status\x18\x01 \x01(\x0e\x32\x10.app.enum.Status*P\n\x06Status\x12\x12\n\x0eSTATUS_DEFAULT\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x0f\n\x0bSTATUS_FAIL\x10\x02\x12\x12\n\x0eSTATUS_TIMEOUT\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=71
  _globals['_STATUS']._serialized_end=151
  _globals['_PINGREPLY']._serialized_start=24
  _globals['_PINGREPLY']._serialized_end=69
# @@protoc_insertion_point(module_scope)
