"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Status:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Status.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STATUS_DEFAULT: _Status.ValueType  # 0
    STATUS_OK: _Status.ValueType  # 1
    STATUS_FAIL: _Status.ValueType  # 2
    STATUS_TIMEOUT: _Status.ValueType  # 3

class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...

STATUS_DEFAULT: Status.ValueType  # 0
STATUS_OK: Status.ValueType  # 1
STATUS_FAIL: Status.ValueType  # 2
STATUS_TIMEOUT: Status.ValueType  # 3
global___Status = Status

@typing.final
class PingReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: global___Status.ValueType
    def __init__(
        self,
        *,
        status: global___Status.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___PingReply = PingReply
