# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: map.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'map.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmap.proto\x12\x07\x61pp.map\"k\n\x08Platform\x12/\n\x07scrapli\x18\x01 \x03(\x0b\x32\x1e.app.map.Platform.ScrapliEntry\x1a.\n\x0cScrapliEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLATFORM_SCRAPLIENTRY']._loaded_options = None
  _globals['_PLATFORM_SCRAPLIENTRY']._serialized_options = b'8\001'
  _globals['_PLATFORM']._serialized_start=22
  _globals['_PLATFORM']._serialized_end=129
  _globals['_PLATFORM_SCRAPLIENTRY']._serialized_start=83
  _globals['_PLATFORM_SCRAPLIENTRY']._serialized_end=129
# @@protoc_insertion_point(module_scope)
