# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x0b\x61pp.message\"\'\n\x07\x41\x64\x64ress\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0e\n\x06street\x18\x02 \x01(\t\"H\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12%\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32\x14.app.message.Address\"j\n\x08Response\x12,\n\x06status\x18\x01 \x01(\x0b\x32\x1c.app.message.Response.Result\x12\x0c\n\x04text\x18\x02 \x01(\t\x1a\"\n\x06Result\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDRESS']._serialized_start=30
  _globals['_ADDRESS']._serialized_end=69
  _globals['_USER']._serialized_start=71
  _globals['_USER']._serialized_end=143
  _globals['_RESPONSE']._serialized_start=145
  _globals['_RESPONSE']._serialized_end=251
  _globals['_RESPONSE_RESULT']._serialized_start=217
  _globals['_RESPONSE_RESULT']._serialized_end=251
# @@protoc_insertion_point(module_scope)
