"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Event(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEXT_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    text: builtins.str
    code: builtins.int
    def __init__(
        self,
        *,
        text: builtins.str = ...,
        code: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["code", b"code", "payload", b"payload", "text", b"text"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "payload", b"payload", "text", b"text"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["payload", b"payload"]) -> typing.Literal["text", "code"] | None: ...

global___Event = Event
