# ruff: noqa
# mypy: ignore-errors
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ping.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "ping.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nping.proto\x12\x0b\x61pp.ping.v1",\n\x0bPingRequest\x12\x0e\n\x06target\x18\n \x01(\t\x12\r\n\x05\x64\x65lay\x18\x14 \x01(\x05"3\n\tPingReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\r\n\x05\x64\x65lay\x18\x03 \x01(\x05" \n\x0cHelloRequest\x12\x10\n\x08username\x18\x01 \x01(\t"\'\n\nHelloReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\x05\x32G\n\x0bPingService\x12\x38\n\x04Ping\x12\x18.app.ping.v1.PingRequest\x1a\x16.app.ping.v1.PingReply2K\n\x0cHelloService\x12;\n\x05Hello\x12\x19.app.ping.v1.HelloRequest\x1a\x17.app.ping.v1.HelloReplyb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ping_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PINGREQUEST"]._serialized_start = 27
    _globals["_PINGREQUEST"]._serialized_end = 71
    _globals["_PINGREPLY"]._serialized_start = 73
    _globals["_PINGREPLY"]._serialized_end = 124
    _globals["_HELLOREQUEST"]._serialized_start = 126
    _globals["_HELLOREQUEST"]._serialized_end = 158
    _globals["_HELLOREPLY"]._serialized_start = 160
    _globals["_HELLOREPLY"]._serialized_end = 199
    _globals["_PINGSERVICE"]._serialized_start = 201
    _globals["_PINGSERVICE"]._serialized_end = 272
    _globals["_HELLOSERVICE"]._serialized_start = 274
    _globals["_HELLOSERVICE"]._serialized_end = 349
# @@protoc_insertion_point(module_scope)
