inventory:
  plugin: SimpleInventory
  options:
    host_file: ./14.nornir/src/23.edit_acl/inventory/hosts.yaml
    group_file: ./14.nornir/src/23.edit_acl/inventory/groups.yaml
    defaults_file: ./14.nornir/src/23.edit_acl/inventory/defaults.yaml
logging:
  enabled: false
runner:
  plugin: threaded
  options:
    num_workers: 1
