"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TARGET_FIELD_NUMBER: builtins.int
    DELAY_FIELD_NUMBER: builtins.int
    target: builtins.str
    delay: builtins.int
    def __init__(
        self,
        *,
        target: builtins.str = ...,
        delay: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["delay", b"delay", "target", b"target"]) -> None: ...

global___PingRequest = PingRequest

@typing.final
class PingReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    DELAY_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    msg: builtins.str
    delay: builtins.int
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
        msg: builtins.str = ...,
        delay: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["delay", b"delay", "msg", b"msg", "ok", b"ok"]) -> None: ...

global___PingReply = PingReply
