inventory:
  plugin: SimpleInventory
  options:
    host_file: ./14.nornir/src/16.processor/inventory/hosts.yaml
    group_file: ./14.nornir/src/16.processor/inventory/groups.yaml
    defaults_file: ./14.nornir/src/16.processor/inventory/defaults.yaml
logging:
  enabled: true
runner:
  plugin: threaded
  options:
    num_workers: 1
