"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
однострочный комментарий
имя пакета
inline комментарий
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PingRequest(google.protobuf.message.Message):
    """
    многострочный
    комментарии

    входящее сообщение (аргументы функции)
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TARGET_FIELD_NUMBER: builtins.int
    OK_FIELD_NUMBER: builtins.int
    target: builtins.str
    ok: builtins.bool
    def __init__(
        self,
        *,
        target: builtins.str = ...,
        ok: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ok", b"ok", "target", b"target"]) -> None: ...

global___PingRequest = PingRequest

@typing.final
class PingReply(google.protobuf.message.Message):
    """выходящее сообщение (результат работы функции)"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ok", b"ok"]) -> None: ...

global___PingReply = PingReply
