# ruff: noqa
# mypy: ignore-errors
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "hello.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bhello.proto\x12\x0c\x61pp.hello.v1"*\n\x0cHelloRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\r\n\x05\x64\x65lay\x18\x02 \x01(\x05"\xb1\x01\n\rHelloResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\r\n\x05\x64\x65lay\x18\x02 \x01(\x05\x12\x32\n\x06status\x18\n \x01(\x0e\x32".app.hello.v1.HelloResponse.Status"P\n\x06Status\x12\x12\n\x0eSTATUS_DEFAULT\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x0f\n\x0bSTATUS_FAIL\x10\x02\x12\x12\n\x0eSTATUS_TIMEOUT\x10\x03\x32P\n\x0cHelloService\x12@\n\x05Hello\x12\x1a.app.hello.v1.HelloRequest\x1a\x1b.app.hello.v1.HelloResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "hello_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_HELLOREQUEST"]._serialized_start = 29
    _globals["_HELLOREQUEST"]._serialized_end = 71
    _globals["_HELLORESPONSE"]._serialized_start = 74
    _globals["_HELLORESPONSE"]._serialized_end = 251
    _globals["_HELLORESPONSE_STATUS"]._serialized_start = 171
    _globals["_HELLORESPONSE_STATUS"]._serialized_end = 251
    _globals["_HELLOSERVICE"]._serialized_start = 253
    _globals["_HELLOSERVICE"]._serialized_end = 333
# @@protoc_insertion_point(module_scope)
