# ruff: noqa
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class HelloRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MSG_FIELD_NUMBER: builtins.int
    DELAY_FIELD_NUMBER: builtins.int
    msg: builtins.str
    delay: builtins.int
    def __init__(
        self,
        *,
        msg: builtins.str = ...,
        delay: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["delay", b"delay", "msg", b"msg"]) -> None: ...

global___HelloRequest = HelloRequest

@typing.final
class HelloResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Status:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusEnumTypeWrapper(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[HelloResponse._Status.ValueType], builtins.type
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STATUS_DEFAULT: HelloResponse._Status.ValueType  # 0
        STATUS_OK: HelloResponse._Status.ValueType  # 1
        STATUS_FAIL: HelloResponse._Status.ValueType  # 2
        STATUS_TIMEOUT: HelloResponse._Status.ValueType  # 3

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    STATUS_DEFAULT: HelloResponse.Status.ValueType  # 0
    STATUS_OK: HelloResponse.Status.ValueType  # 1
    STATUS_FAIL: HelloResponse.Status.ValueType  # 2
    STATUS_TIMEOUT: HelloResponse.Status.ValueType  # 3

    MSG_FIELD_NUMBER: builtins.int
    DELAY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    msg: builtins.str
    delay: builtins.int
    status: global___HelloResponse.Status.ValueType
    def __init__(
        self,
        *,
        msg: builtins.str = ...,
        delay: builtins.int = ...,
        status: global___HelloResponse.Status.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["delay", b"delay", "msg", b"msg", "status", b"status"]) -> None: ...

global___HelloResponse = HelloResponse
