# ruff: noqa
# mypy: ignore-errors
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ping.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "ping.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nping.proto\x12\x0b\x61pp.ping.v1"\x1d\n\x0bPingRequest\x12\x0e\n\x06target\x18\n \x01(\t"$\n\tPingReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t2G\n\x0bPingService\x12\x38\n\x04Ping\x12\x18.app.ping.v1.PingRequest\x1a\x16.app.ping.v1.PingReplyb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ping_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PINGREQUEST"]._serialized_start = 27
    _globals["_PINGREQUEST"]._serialized_end = 56
    _globals["_PINGREPLY"]._serialized_start = 58
    _globals["_PINGREPLY"]._serialized_end = 94
    _globals["_PINGSERVICE"]._serialized_start = 96
    _globals["_PINGSERVICE"]._serialized_end = 167
# @@protoc_insertion_point(module_scope)
