inventory:
  plugin: SimpleInventory
  options:
    host_file: ./c14_nornir/src/01.quick_example/inventory/hosts.yaml
    group_file: ./c14_nornir/src/01.quick_example/inventory/groups.yaml
    defaults_file: ./c14_nornir/src/01.quick_example/inventory/defaults.yaml

logging:
  enabled: True

runner:
  plugin: threaded
  options:
    num_workers: 20
