"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _TraceOperation:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TraceOperationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TraceOperation.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Operation_notset: _TraceOperation.ValueType  # 0
    Operation_unknown: _TraceOperation.ValueType  # 1
    Operation_write: _TraceOperation.ValueType  # 2
    Operation_read: _TraceOperation.ValueType  # 3

class TraceOperation(_TraceOperation, metaclass=_TraceOperationEnumTypeWrapper): ...

Operation_notset: TraceOperation.ValueType  # 0
Operation_unknown: TraceOperation.ValueType  # 1
Operation_write: TraceOperation.ValueType  # 2
Operation_read: TraceOperation.ValueType  # 3
global___TraceOperation = TraceOperation

class _DeviceResultStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DeviceResultStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DeviceResultStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Device_notset: _DeviceResultStatus.ValueType  # 0
    Device_ok: _DeviceResultStatus.ValueType  # 1
    Device_error: _DeviceResultStatus.ValueType  # 2

class DeviceResultStatus(_DeviceResultStatus, metaclass=_DeviceResultStatusEnumTypeWrapper): ...

Device_notset: DeviceResultStatus.ValueType  # 0
Device_ok: DeviceResultStatus.ValueType  # 1
Device_error: DeviceResultStatus.ValueType  # 2
global___DeviceResultStatus = DeviceResultStatus

class _FileStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _FileStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_FileStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    FileStatus_notset: _FileStatus.ValueType  # 0
    FileStatus_ok: _FileStatus.ValueType  # 1
    FileStatus_error: _FileStatus.ValueType  # 2
    FileStatus_not_found: _FileStatus.ValueType  # 3
    FileStatus_is_dir: _FileStatus.ValueType  # 4

class FileStatus(_FileStatus, metaclass=_FileStatusEnumTypeWrapper): ...

FileStatus_notset: FileStatus.ValueType  # 0
FileStatus_ok: FileStatus.ValueType  # 1
FileStatus_error: FileStatus.ValueType  # 2
FileStatus_not_found: FileStatus.ValueType  # 3
FileStatus_is_dir: FileStatus.ValueType  # 4
global___FileStatus = FileStatus

@typing.final
class QA(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUESTION_FIELD_NUMBER: builtins.int
    ANSWER_FIELD_NUMBER: builtins.int
    NOT_SEND_NL_FIELD_NUMBER: builtins.int
    question: builtins.str
    answer: builtins.str
    not_send_nl: builtins.bool
    def __init__(
        self,
        *,
        question: builtins.str = ...,
        answer: builtins.str = ...,
        not_send_nl: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["answer", b"answer", "not_send_nl", b"not_send_nl", "question", b"question"]) -> None: ...

global___QA = QA

@typing.final
class Credentials(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOGIN_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    login: builtins.str
    password: builtins.str
    def __init__(
        self,
        *,
        login: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["login", b"login", "password", b"password"]) -> None: ...

global___Credentials = Credentials

@typing.final
class CMD(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOST_FIELD_NUMBER: builtins.int
    CMD_FIELD_NUMBER: builtins.int
    TRACE_FIELD_NUMBER: builtins.int
    QA_FIELD_NUMBER: builtins.int
    READ_TIMEOUT_FIELD_NUMBER: builtins.int
    CMD_TIMEOUT_FIELD_NUMBER: builtins.int
    STRING_RESULT_FIELD_NUMBER: builtins.int
    HOST_PARAMS_FIELD_NUMBER: builtins.int
    host: builtins.str
    cmd: builtins.str
    trace: builtins.bool
    read_timeout: builtins.float
    cmd_timeout: builtins.float
    string_result: builtins.bool
    @property
    def qa(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___QA]: ...
    @property
    def host_params(self) -> global___HostParams: ...
    def __init__(
        self,
        *,
        host: builtins.str = ...,
        cmd: builtins.str = ...,
        trace: builtins.bool = ...,
        qa: collections.abc.Iterable[global___QA] | None = ...,
        read_timeout: builtins.float = ...,
        cmd_timeout: builtins.float = ...,
        string_result: builtins.bool = ...,
        host_params: global___HostParams | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["host_params", b"host_params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cmd", b"cmd", "cmd_timeout", b"cmd_timeout", "host", b"host", "host_params", b"host_params", "qa", b"qa", "read_timeout", b"read_timeout", "string_result", b"string_result", "trace", b"trace"]) -> None: ...

global___CMD = CMD

@typing.final
class Device(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PROMPT_EXPRESSION_FIELD_NUMBER: builtins.int
    ERROR_EXPRESSION_FIELD_NUMBER: builtins.int
    PAGER_EXPRESSION_FIELD_NUMBER: builtins.int
    name: builtins.str
    prompt_expression: builtins.str
    error_expression: builtins.str
    pager_expression: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        prompt_expression: builtins.str = ...,
        error_expression: builtins.str = ...,
        pager_expression: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_expression", b"error_expression", "name", b"name", "pager_expression", b"pager_expression", "prompt_expression", b"prompt_expression"]) -> None: ...

global___Device = Device

@typing.final
class CMDNetconf(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOST_FIELD_NUMBER: builtins.int
    CMD_FIELD_NUMBER: builtins.int
    JSON_FIELD_NUMBER: builtins.int
    READ_TIMEOUT_FIELD_NUMBER: builtins.int
    CMD_TIMEOUT_FIELD_NUMBER: builtins.int
    host: builtins.str
    cmd: builtins.str
    json: builtins.bool
    read_timeout: builtins.float
    cmd_timeout: builtins.float
    def __init__(
        self,
        *,
        host: builtins.str = ...,
        cmd: builtins.str = ...,
        json: builtins.bool = ...,
        read_timeout: builtins.float = ...,
        cmd_timeout: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cmd", b"cmd", "cmd_timeout", b"cmd_timeout", "host", b"host", "json", b"json", "read_timeout", b"read_timeout"]) -> None: ...

global___CMDNetconf = CMDNetconf

@typing.final
class CMDTraceItem(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATION_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    operation: global___TraceOperation.ValueType
    data: builtins.bytes
    def __init__(
        self,
        *,
        operation: global___TraceOperation.ValueType = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "operation", b"operation"]) -> None: ...

global___CMDTraceItem = CMDTraceItem

@typing.final
class HostParams(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOST_FIELD_NUMBER: builtins.int
    CREDENTIALS_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    DEVICE_FIELD_NUMBER: builtins.int
    IP_FIELD_NUMBER: builtins.int
    host: builtins.str
    port: builtins.int
    device: builtins.str
    ip: builtins.str
    @property
    def credentials(self) -> global___Credentials: ...
    def __init__(
        self,
        *,
        host: builtins.str = ...,
        credentials: global___Credentials | None = ...,
        port: builtins.int = ...,
        device: builtins.str = ...,
        ip: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["credentials", b"credentials"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["credentials", b"credentials", "device", b"device", "host", b"host", "ip", b"ip", "port", b"port"]) -> None: ...

global___HostParams = HostParams

@typing.final
class CMDResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OUT_FIELD_NUMBER: builtins.int
    OUT_STR_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    ERROR_STR_FIELD_NUMBER: builtins.int
    TRACE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    out: builtins.bytes
    out_str: builtins.str
    error: builtins.bytes
    error_str: builtins.str
    status: builtins.int
    @property
    def trace(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CMDTraceItem]: ...
    def __init__(
        self,
        *,
        out: builtins.bytes = ...,
        out_str: builtins.str = ...,
        error: builtins.bytes = ...,
        error_str: builtins.str = ...,
        trace: collections.abc.Iterable[global___CMDTraceItem] | None = ...,
        status: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "error_str", b"error_str", "out", b"out", "out_str", b"out_str", "status", b"status", "trace", b"trace"]) -> None: ...

global___CMDResult = CMDResult

@typing.final
class DeviceResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RES_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    res: global___DeviceResultStatus.ValueType
    error: builtins.str
    def __init__(
        self,
        *,
        res: global___DeviceResultStatus.ValueType = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "res", b"res"]) -> None: ...

global___DeviceResult = DeviceResult

@typing.final
class FileDownloadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOST_FIELD_NUMBER: builtins.int
    PATHS_FIELD_NUMBER: builtins.int
    DEVICE_FIELD_NUMBER: builtins.int
    HOST_PARAMS_FIELD_NUMBER: builtins.int
    host: builtins.str
    device: builtins.str
    @property
    def paths(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def host_params(self) -> global___HostParams: ...
    def __init__(
        self,
        *,
        host: builtins.str = ...,
        paths: collections.abc.Iterable[builtins.str] | None = ...,
        device: builtins.str = ...,
        host_params: global___HostParams | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["host_params", b"host_params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["device", b"device", "host", b"host", "host_params", b"host_params", "paths", b"paths"]) -> None: ...

global___FileDownloadRequest = FileDownloadRequest

@typing.final
class FileData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATH_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    path: builtins.str
    data: builtins.bytes
    status: global___FileStatus.ValueType
    def __init__(
        self,
        *,
        path: builtins.str = ...,
        data: builtins.bytes = ...,
        status: global___FileStatus.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "path", b"path", "status", b"status"]) -> None: ...

global___FileData = FileData

@typing.final
class FileUploadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOST_FIELD_NUMBER: builtins.int
    DEVICE_FIELD_NUMBER: builtins.int
    FILES_FIELD_NUMBER: builtins.int
    HOST_PARAMS_FIELD_NUMBER: builtins.int
    host: builtins.str
    device: builtins.str
    @property
    def files(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FileData]: ...
    @property
    def host_params(self) -> global___HostParams: ...
    def __init__(
        self,
        *,
        host: builtins.str = ...,
        device: builtins.str = ...,
        files: collections.abc.Iterable[global___FileData] | None = ...,
        host_params: global___HostParams | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["host_params", b"host_params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["device", b"device", "files", b"files", "host", b"host", "host_params", b"host_params"]) -> None: ...

global___FileUploadRequest = FileUploadRequest

@typing.final
class FilesResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILES_FIELD_NUMBER: builtins.int
    @property
    def files(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FileData]: ...
    def __init__(
        self,
        *,
        files: collections.abc.Iterable[global___FileData] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["files", b"files"]) -> None: ...

global___FilesResult = FilesResult
