inventory:
  plugin: SimpleInventory
  options:
    host_file: ./14.nornir/src/10.tqdm/inventory/hosts.yaml
    group_file: ./14.nornir/src/10.tqdm/inventory/groups.yaml
    defaults_file: ./14.nornir/src/10.tqdm/inventory/defaults.yaml
logging:
  enabled: True
runner:
  plugin: threaded
  options:
    num_workers: 10
