# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from . import chars_pb2 as chars__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in chars_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CharServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TextToChars = channel.unary_stream(
            "/app.chars.v1.CharService/TextToChars",
            request_serializer=chars__pb2.CharMessage.SerializeToString,
            response_deserializer=chars__pb2.CharMessage.FromString,
            _registered_method=True,
        )


class CharServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TextToChars(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CharServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "TextToChars": grpc.unary_stream_rpc_method_handler(
            servicer.TextToChars,
            request_deserializer=chars__pb2.CharMessage.FromString,
            response_serializer=chars__pb2.CharMessage.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("app.chars.v1.CharService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("app.chars.v1.CharService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class CharService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TextToChars(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/app.chars.v1.CharService/TextToChars",
            chars__pb2.CharMessage.SerializeToString,
            chars__pb2.CharMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
