inventory:
  plugin: SimpleInventory
  options:
    host_file: ./14.nornir/src/17.functions/inventory/hosts.yaml
    group_file: ./14.nornir/src/17.functions/inventory/groups.yaml
    defaults_file: ./14.nornir/src/17.functions/inventory/defaults.yaml

runner:
  plugin: threaded
  options:
    num_workers: 20
