inventory:
  plugin: SimpleInventory
  options:
    host_file: ./14.nornir/src/09.nornir_scrapli_send_configs/inventory/hosts.yaml
    group_file: ./14.nornir/src/09.nornir_scrapli_send_configs/inventory/groups.yaml
    defaults_file: ./14.nornir/src/09.nornir_scrapli_send_configs/inventory/defaults.yaml
logging:
  enabled: True
runner:
  plugin: threaded
  options:
    num_workers: 20
