# ruff: noqa
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Platform:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PlatformEnumTypeWrapper(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Platform.ValueType], builtins.type
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PLATFORM_DEFAULT: _Platform.ValueType  # 0
    PLATFORM_CISCO_IOSXE: _Platform.ValueType  # 10
    PLATFORM_CISCO_IOSXR: _Platform.ValueType  # 20
    PLATFORM_HUAWEI_VRP: _Platform.ValueType  # 30

class Platform(_Platform, metaclass=_PlatformEnumTypeWrapper): ...

PLATFORM_DEFAULT: Platform.ValueType  # 0
PLATFORM_CISCO_IOSXE: Platform.ValueType  # 10
PLATFORM_CISCO_IOSXR: Platform.ValueType  # 20
PLATFORM_HUAWEI_VRP: Platform.ValueType  # 30
global___Platform = Platform

@typing.final
class Host(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOST_FIELD_NUMBER: builtins.int
    PLATFORM_FIELD_NUMBER: builtins.int
    AUTH_USERNAME_FIELD_NUMBER: builtins.int
    AUTH_PASSWORD_FIELD_NUMBER: builtins.int
    AUTH_SECONDARY_FIELD_NUMBER: builtins.int
    host: builtins.str
    platform: global___Platform.ValueType
    auth_username: builtins.str
    auth_password: builtins.str
    auth_secondary: builtins.str
    def __init__(
        self,
        *,
        host: builtins.str = ...,
        platform: global___Platform.ValueType = ...,
        auth_username: builtins.str = ...,
        auth_password: builtins.str = ...,
        auth_secondary: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "auth_password",
            b"auth_password",
            "auth_secondary",
            b"auth_secondary",
            "auth_username",
            b"auth_username",
            "host",
            b"host",
            "platform",
            b"platform",
        ],
    ) -> None: ...

global___Host = Host

@typing.final
class Command(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOST_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    command: builtins.str
    @property
    def host(self) -> global___Host: ...
    def __init__(
        self,
        *,
        host: global___Host | None = ...,
        command: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["host", b"host"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["command", b"command", "host", b"host"]) -> None: ...

global___Command = Command

@typing.final
class Result(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOST_FIELD_NUMBER: builtins.int
    CHANNEL_INPUT_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    ELAPSED_TIME_FIELD_NUMBER: builtins.int
    FAILED_FIELD_NUMBER: builtins.int
    host: builtins.str
    channel_input: builtins.str
    result: builtins.str
    elapsed_time: builtins.float
    failed: builtins.bool
    def __init__(
        self,
        *,
        host: builtins.str = ...,
        channel_input: builtins.str = ...,
        result: builtins.str = ...,
        elapsed_time: builtins.float = ...,
        failed: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "channel_input",
            b"channel_input",
            "elapsed_time",
            b"elapsed_time",
            "failed",
            b"failed",
            "host",
            b"host",
            "result",
            b"result",
        ],
    ) -> None: ...

global___Result = Result
